### ISSUE TITLE
Prob;lem

### ISSUE THREAD

**Issue by Whaaamtrash** [amjoshuamichael/whaaam#6]
yo this programmer ugly asf. pls have this issue fixed soon

**Comment by amjoshuamichael** [comment]
Hey! Thanks for your issue submission. Can you be more specific about this issue, and how it contributes to your experience with the software?

**Comment by Whaaamtrash** [comment]
i look at ur profile picture everyday, and it adds on too my trauma  of u being ugly asf

**Comment by amjoshuamichael** [comment]
Unfortunately, this seems to be an issue with you, and not the program itself. I will close this for being unnecessary.

**Comment by Whaaamtrash** [comment]
yo wtf u stupiad ass bitch fucking asshole cunt., others, including ur family and school think the same. pls get this issue fixed

**Comment by amjoshuamichael** [comment]
Once again, this seems to be an issue _outside_ of the program. Please, take this outside of the Github issues for the software. **I will be locking this conversation.**
